# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1cdfa200c1abde887c4e82e8999ebcb3766e3d595e330a6e6f661218a9f2808f515cb99755f93ef77c33e89240d51fabe0d0465f713c678de06afe05e64afcb

test:
  secret_key_base: 572b51e40a0d47422d9cea59210004be18fb511fdf151dbb762dbea906e0432c747ce7307b0f30230cbafe742c33893e8e6058db0ca075236eb7efe9ba826dae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
